### PR TITLE
Update style-guide: update go style

### PR DESCRIPTION
**Pull request by sdsddsd1**

### CODE REVIEW

**Comment by illiliti** [comment]
Note that building with vendor mod is not always available and depends on how release tarball was packaged. We should keep current style and add note about that building with vendor mod is preferred if available.

**Comment by sdsddsd1** [comment]
How can one check if `-mod=vendor` is available? Is there an unified way?

**Comment by illiliti** [comment]
'vendor' directory should be present in root of extracted source.

**Comment by sdsddsd1** [comment]
Ok it wont get any better. Leaving it now as is.

**Comment by dilyn-corner** [comment]
Damn shame that less than half of the `go` packages we have in `community` have a `vendor` folder, huh. 

lgtm

**Pull request merged**
