### PR TITLE
kernel/firmware: add .config example with complex configuration

### PR DESCRIPTION
**Pull request by sdsddsd1**

### CODE REVIEW

**Comment by sdsddsd1** [comment]
There is often the question on how to solve more complex firmware situations like amdgpu with its multiple files and on to preserve the directory structure. This pr shall cover this case.

**Comment by dilyn-corner** [comment]
I like it, but without disambiguation I think readers might be under the impression that you can write your firmware list exactly as you have here, which is sadly not the case. It's hard to say how exactly it should be written to make it as clear as possible...
We should also include a menuconfig example, I think.

**Comment by sdsddsd1** [comment]
Yes I had this thought too, that this style of presentation might be misleading too. I went for a simple and general aproach now.

**Comment by dilyn-corner** [comment]
Excellente. I am content.

**Pull request merged**
